applications/server/project.json
packages/cs-parser/project.json

Fix release:all scripts in server and parser to build with platform "win" instead of incorrect "windows"

Fix windows build platform

---

.changeset/config.json
applications/client/src/components/Dialogs/UserSettingsOverlay.tsx
applications/redeye-e2e/cypress.config.js

User setting text is in dot notation
View #18 for testing steps
Check that the User Setting user.name is now Username
in code comments.
to reflect the changes in this PR.

closes User setting displaying incorrect data

---

applications/client/src/views/Campaign/Explore/Panels/Meta/BeaconMeta.tsx

Bugfix for Beacon Meta:
- Fixed timezone auto-rerender
- Fixed timezone conversion being applied twice

Bugfix - beacon meta timezone

---

applications/client/src/views/Campaigns/AnonymizeDialog/AnonymizeDialog.tsx
applications/server/src/machines/anonymization/anonymization.machine.ts
applications/server/src/machines/anonymization/anonymization.machine.typegen.ts
applications/server/src/store/campaign-resolvers.ts

Move anonymization machine to final state if error occurs during anonymization
Print debug log for anonymization error

Small fix for anonymization & export error state

---

applications/server/package.json
applications/server/src/machines/anonymization/anonymize.service.ts

Explicitly includes path to export worker script in pkg config

Fix executable sometimes not finding export worker script

---

applications/client/src/views/Campaign/Explore/Panels/Beacon/Beacon.tsx
applications/client/src/views/Campaign/Explore/Panels/Host/Host.tsx
applications/client/src/views/Campaign/Explore/Panels/Meta/use-toggle-hidden.ts
applications/client/src/views/Campaign/Explore/Panels/QuickMeta.tsx
applications/client/src/views/Campaign/Timeline/BarLabels.tsx
applications/client/src/views/Campaign/Timeline/Bars.tsx
applications/server/src/store/command-group-resolvers.ts

Resolve #6
- When "Show Hidden Beacons, Host, and Servers" toggle is off,
-- quick editing button to hide a Server/Host/Beacon 
- When "Show Hidden Beacons, Host, and Servers" toggle is on, 
-- quick editing button to Show/Hide a Server/Host/Beacon
-- a viewOff icon to indicate it's hidden
- Show/Hide Beacon will route to Beacons Tab instead of Hosts Tab

Quick metadata editing for Server/Host/Beacon

---

applications/client/src/views/Campaign/Explore/Panels/Beacon/Beacon.tsx
applications/client/src/views/Campaign/Explore/Panels/Host/Host.tsx
applications/client/src/views/Campaign/Explore/Panels/Meta/HideDialog.tsx
applications/client/src/views/Campaign/Explore/Panels/QuickMeta.tsx
applications/client/src/views/Campaign/Explore/components/IconLabel.tsx

- Hiding a server/host/beacon will open the confirmation modal
-- Will add a "don't show this again" checkbox in next Quick Meta update PR.
- Move the viewOff hidden indicator icon to the start of the icon group on the right side
- Change the quick meta icon to a button and css change
- Disable show/hide for blueteam

Quick Meta button update

---

README.md
applications/client/src/components/Header/AppOptions.tsx
applications/client/src/components/Header/ModeIndicator.tsx
applications/client/src/views/Campaigns/Upload/NewCampaignDialog.tsx
applications/redeye-e2e/src/integration/e2e/blueteam/verify-blueteam-version.cy.js
applications/server/src/asciiArt.ts
applications/server/src/machines/http.service.ts

NOTE! this PR is stacked onto `add-campaign-form-tweaks` so that the diff is more accurate. So when it's merged, we will need to make sure the right changes are added to `develop`. 
- updated Readme - see [Github preview](https://github.com/cisagov/RedEye/tree/red-team-blue-team-disambiguation#readme)
- Add a mode indicator to the Server log output
- Added a full text description of Red/Blue Team on the homepage
- Added a link from the Red/Blue Team ModeIndicator Popover to the (future) ReadMe.md.
- Read [ReadMe.md](https://github.com/cisagov/RedEye/tree/red-team-blue-team-disambiguation#readme)
- Does the server log output include the proper Red or Blue team output?

Red Team / Blue Team Disambiguation

---

applications/client/src/views/Campaign/Explore/Panels/QuickMeta.tsx
packages/ui-styles/src/components/PopoverButton.tsx

Before this fix, clicking 'cancel' in the ToggleHiddenDialog would not close the QuickMetaPopoverButtonMenu. Now, with the correct set of `e.stopPropagation()`s in our events. This works as its supposed to. Still not 100% sure why a click event in a detached Portal Dialog was triggering a click event on the InfoRow... but it works now.
- Show/Hide Beacon/Host/Server functionality
- with and without the 'Don't show this warning again' checked. To disable this go to devtools > Application >LocalStorage > localhost:3500 > and delete 'disableDialog' from the list (see screenshot)

Close the QuickMetaPopoverButtonMenu when ToggleHiddenDialog is closed

---

applications/client/src/components/DragResize.tsx
packages/ui-styles/src/components/Text.tsx

Give the text content in the left panel more room for readability.
- Left Panel is now a bit larger by default - 600px
- Left Panel now persists its resize between page reloads using window.localStorage
- The drag resize now more precise
- css grid layout is simplified
- Double clicking the dragger will reset the left panel to the default size
- I made a commit that persists the collapsed state of either panel, but the graph does not initialize properly if the panel its in starts collapsed. I reverted that change and left a note.
- drag resize the left panel
- reload the page

Persist Left Panel Resize

---

.github/workflows/test.yml
applications/redeye-e2e/src/integration/e2e/redteam/mitre-attack.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/multi-command-comment.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/timeline.cy.js

Quick fix to cypress workflow for fixing broken blue team builds

fixes broken builds for blue team

---

applications/client/src/components/Forms/LoginForm.tsx
applications/client/src/store/auth.ts
applications/client/src/views/Campaign/Explore/components/Comment/CommentBox.tsx

- Support auto save pending comments when creating new comments or reply to comments, even after the comment box is closed by any action
- Should support autosave for multiple commands - auto save and associate the pending comments to each corresponding command
- Should keep pending comments associated to the specific command across the campaign, including routing to other tabs via breadcrumb or refresh
- Will clear pending comments after hitting Submit or Cancel button
- Will clear pending comments after logout, or login with a different username

Autosave multi pending comments

---

applications/client/src/components/Mitre/MitreAttack.tsx
applications/client/src/views/Campaign/Explore/Panels/Command/CommandOutput.tsx

The `MitreAttack` component contained a 'no property of undefined' bug that crashed the app. Also added a missing array.map() key prop.
See diff for details

Hotfix: MitreAttack component crashes the app

---

applications/client/src/store/campaign/campaign.ts
applications/client/src/views/Campaign/Explore/Panels/Comment/CommentGroup.tsx
applications/client/src/views/Campaign/Explore/Panels/Comment/Comments.tsx
applications/client/src/views/Campaign/Explore/Panels/Comment/CommentsList.tsx
applications/client/src/views/Campaign/Presentation/PresentationItem.tsx
applications/redeye-e2e/src/integration/e2e/redteam/add-delete-comments.cy.js
applications/server/schema.graphql

The Comments virtualized list scrolling was unusable. It jumped all over the place while scrolling. There were 2 issues 
- there was a sneaky margin leaking out of the CommentGroup that was Virtuoso's renderItem. ["Setting CSS margins to the content or the item elements is the Kryptonite of Virtuoso's content measuring mechanism"](https://virtuoso.dev/#gotchas:~:text=Setting%20CSS%20margins%20to%20the%20content%20or%20the%20item%20elements%20is%20the%20Kryptonite%20of%20Virtuoso%27s%20content%20measuring%20mechanism). This was fixed by adding a 1px vertical padding
- There was a circular dependency in `Comments.tsx` useEffect. The useEffect body updated a property that was also set as a dependency of the useEffect. This caused constant re-rendering of the list.
Some of the Comment list …

Comments virtualized list bugs

---

applications/client/src/store/graphql/CommandModel.ts
applications/client/src/store/graphql/HostModel.ts
applications/client/src/store/graphql/ServerModel.ts
applications/client/src/views/Campaign/Explore/components/NavBreadcrumbs.tsx

Beacons can only be connected to one server (I think?), so they have a hierarchical location path like 'Server / Host / Beacon.' However, Hosts can contain Beacons that are connected to different Servers, so Hosts can be associated with more than one server. This PR removes the Server from the Host path until the data structure can be adjusted. 
- validate that host paths don't display an associated Server
- validate that beacon paths do display the assoicated Server

Remove Servers from Host Path

---

applications/client/src/types/explore.ts
applications/client/src/views/Campaign/Explore/Panels/Command/CommandOutput.tsx
applications/client/src/views/Campaign/Explore/Panels/Comment/CommentsList.tsx
applications/client/src/views/Campaign/Explore/Panels/Panels.tsx
applications/client/src/views/Campaign/Explore/components/Comment/CommentBox.tsx
applications/client/src/views/Campaign/Explore/components/IconLabel.tsx
applications/client/src/views/Campaign/Presentation/PresentationTopicItem.tsx
applications/redeye-e2e/src/integration/e2e/blueteam/details-tab.cy.js
applications/redeye-e2e/src/integration/e2e/blueteam/hide-show-beacon.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/details-tab-links.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/hide-show-beacon.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/hide-show-host.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/hide-show-server.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/update-beacon-details.skip.js
applications/redeye-e2e/src/support/command.d.ts
applications/redeye-e2e/src/support/explore.js

Several minor tweaks based on user feedback
- Added `[input]` log line Command expanded lines so a user can read the full input when it gets truncated in the initial preview
- Changed the icon for Favorites from a Bookmark to a Star
- Tag input has simple validation that adds the '#' as you type for more consistency with the `#TagName` rendering
- Typing the '#' or not will have the same visual result
- rename the 'Meta' tab to 'Details' because users to not understand what 'Meta' is meant to mean
Test that the above is true, especially the `#Tag` input on the comments

Minor Label Tweaks

---

applications/client/src/views/Campaign/Explore/Panels/Beacon/BeaconRow.tsx

1 line fix to remove the duplicate beacon name in BeaconRow.

Remove the duplicate beacon name in BeaconRow

---

applications/client/vite.config.ts
applications/redeye-e2e/cypress.config.js
applications/redeye-e2e/src/support/commands.js
package.json
yarn.lock

update vite to work with cypress
Added host: true to vite.config.js

update vite to work with cypress

---

.github/workflows/test.yml
.moon/tasks.yml
applications/client/src/env.d.ts
applications/client/src/store/auth.ts
applications/redeye-e2e/moon.yml
applications/redeye-e2e/src/integration/e2e/redteam/graphql/hide-beacon-bulk.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/graphql/hide-beacon.cy.js
applications/redeye-e2e/src/integration/e2e/redteam/uploadRawLogs.cy.js
applications/server/src/store/command-resolvers.ts
package.json

- Use a built version of the client for cypress tests to improve performance
- Change beacon count for raw logs test because we've removed the server beacon from the count 
- Change beacon name for hide-beacon tests because they have been updated to display different information 
- Catch command type endpoint error and return empty array

Small Test Updates

---

applications/client/src/views/Campaign/Search/util.tsx

- fix bug chaining incorrect property in `getPath`

Bug Fix - beacon name was missing from SearchRows
