- .changeset/afraid-doors-occur.md
- applications/client/src/views/Campaigns/Upload/LogsUpload.tsx
Signed-off-by: GoldingAustin <austin.golding.dev@icloud.com>
Fixes #10
> Fix add campaign dialog description spacing closes #10

- applications/server/project.json
- package.json
- packages/cs-parser/project.json
- yarn.lock
Fix #30
Fix #13
Fetch pkg binary manually to sidestep issue with pkg failing to download
> PKG No such file or directory error

- packages/models/src/projectModels/HostMeta.ts
> Fix hidden hosts failing to delete during anonymization

- .github/workflows/build.yml
- Dockerfile
in code comments.
to reflect the changes in this PR.
> Explicit pkg fetch

- applications/server/src/machines/server.machine.ts
> Add error message to http server close

- applications/server/src/machines/parser.machine.ts
Set database mode to dev_persist in parsing machine when not in production to prevent the database from being cleaned on upload of log files
> Bugfix: dev_clean mode

- applications/client/src/components/Forms/LoginForm.tsx
- applications/client/src/components/Forms/UsernameInput.tsx
- applications/client/src/store/graphql/RootStore.base.ts
- applications/redeye-e2e/src/integration/e2e/redteam/graphql/globalOperators.cy.js
- applications/server/src/store/operator-resolvers.ts
- applications/server/src/store/progress-resolvers.ts
Add custom auth middleware for global operator graphql query and mutation
Update login form with feedback that creating a new user is disabled 
Closes #55
> Update global operators graphql query & mutation auth

- .changeset/little-beans-hammer.md
- applications/server/schema.graphql
- packages/models/src/projectModels/BeaconMeta.ts
Exposing this in order to unblock future metadata display features
> Exposing BeaconMeta source LogLine

- applications/server/src/store/command-group-resolvers.ts
Fix commandGroup query to work for show hidden beacon toggle on/off
> Fix commandGroup query

- applications/client/src/components/Header/ModeIndicator.tsx
- applications/redeye-e2e/src/integration/e2e/blueteam/blue-team-check.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/red-team-check.cy.js
Quick test to verify the recent feature for indicating whether the RT/BT version is opened
> Test to verify RT/BT version icon feature

- applications/redeye-e2e/src/integration/e2e/redteam/username-on-comments.cy.js
Quick fix for failing username test
> fix username test

- applications/client/src/components/Dialogs/HelpOverlay.tsx
- applications/client/src/components/Header/AppOptions.tsx
- applications/client/src/views/Campaign/Explore/Panels/Beacon/Beacon.tsx
- applications/client/src/views/Campaign/Explore/Panels/Meta/HideDialog.tsx
- applications/client/src/views/Campaign/Explore/Panels/Meta/HostMeta.tsx
- applications/client/src/views/Campaign/Explore/Panels/Meta/ServerMeta.tsx
- applications/client/src/views/Campaign/Explore/Panels/Overview/OverviewHosts.tsx
- applications/client/src/views/Campaign/Explore/Panels/QuickMeta.tsx
- applications/redeye-e2e/src/integration/e2e/blueteam/hide-show-beacon.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/about-modal.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/command-count.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/golden-ticket.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/hide-show-beacon.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/hide-show-host.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/hide-show-server.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/lateral-movement.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/multi-command-comment.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/multiple-tag-icons-GT-LM-PE.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/multiple-tag-icons-GT-LM.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/multiple-tag-icons-GT-PE.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/multiple-tag-icons-LM-PE.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/privilege-escalation.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/timeline.cy.js
- applications/redeye-e2e/src/support/campaignCard.js
- applications/redeye-e2e/src/support/command.d.ts
- applications/redeye-e2e/src/support/commands.js
- applications/redeye-e2e/src/support/explore.js
- Updates to timeline tests to verify comments are within appropriate timeframe.
- Added new tests for hiding/showing servers and hosts.
- Updated hide/show beacons test to add new check for hiding/showing via kebab menu.
- Minor updates to streamline other tests.
- Added associated data selectors and commands.
> Timeline test updates + refactoring

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- package.json
- yarn.lock
Small update to github actions to fix git error when run manually
> Update moon and github actions

- applications/client/src/views/Campaign/Explore/Panels/Comment/CommentGroup.tsx
- applications/client/src/views/Campaign/Presentation/Presentation.tsx
Fixed Presentation slide bugs
- comment group panel doesn't rerender when back and forth buttons, Finish buttons, or dropdown changes
> Presentation slide bugfix

- .gitignore
> update .gitignore to include server/dev-databases and server/campaign

- applications/client/src/views/Campaign/Explore/Explore.tsx
Maintain timeline scrubber time.
> Timeline Refine - Maintain scrubberTime

- .moon/tasks.yml
- applications/client/moon.yml
- applications/redeye-e2e/moon.yml
- applications/server/.swcrc
- applications/server/moon.yml
- package.json
- packages/cs-parser/.swcrc
- packages/models/.swcrc
- yarn.lock
Fix development command in Windows environments
> Updates for windows

- applications/client/src/views/Campaign/Explore/components/Comment/CommentBox.tsx
Disable comment submit button when no comment content
> Disable comment submit button when no comment content

- applications/client/src/views/Campaign/Graph/Graph.tsx
- packages/graph/moon.yml
- packages/graph/package.json
- packages/graph/src/GraphHandler.ts
- packages/graph/tsconfig.json
- yarn.lock
- The graph export button now uses the correct theme
- removed the graph dependency on ui-styles package
> Fix bug: theme graph export png

- README.md
Minor tweaks to the Readme.md. See diff
> update Readme grammar

- .github/workflows/release.yml
- .moon/tasks.yml
- .moon/toolchain.yml
- Dockerfile
- applications/server/package.json
- packages/cs-parser/package.json
- scripts/release-artifacts.sh
Release script now runs in Docker to prevent future issues with GitHub actions
> Fix release workflow

- applications/client/src/views/Campaign/Presentation/PresentationItem.tsx
For either single or multi commands comments under presentation mode, only the first expanding and collapsing works. After that, expanded commands can't be collapsed any more.
Bug should be fixed by this PR.
> Presentation mode expanding/collapsing bugfix

- applications/landing-page/dist-landing/index.html
- applications/landing-page/src/components/README.md
Fix the userGuide link due to previous file rename
> UserGuide link update

- applications/client/src/views/Campaign/Explore/components/Comment/CommentBox.tsx
- applications/redeye-e2e/src/integration/e2e/redteam/graphql/hide-beacon-bulk.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/graphql/hide-beacon.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/graphql/update-beacon-type.cy.js
Presentation View: allow editing a comment
(This feature was implemented previously #160 , but probably there was a miss when resolving conflicts in a later PR...)
> Presentation View: allow editing a comment Hotfix

- applications/client/src/views/Campaign/Explore/Panels/hooks/use-beacons.ts
- applications/redeye-e2e/src/integration/e2e/redteam/graphql/hide-beacon-bulk.cy.js
- Fix Operator / Beacon tab not rendering beacon list issue
> Operator / Beacon tab bugfix

- applications/client/src/store/campaign/interaction-state.ts
Fix Timeline bars not being highlighted when selecting Host and Servers from Graph
> Graph node timeline selection

- applications/redeye-e2e/moon.yml
- applications/server/src/machines/http.service.ts
- applications/server/src/machines/parser.service.ts
- applications/server/src/store/parser-resolvers.ts
Update vite to use build for local, preview for ci/cd
> Windows dev parsers debug

- applications/client/src/store/campaign/interaction-state.ts
- applications/client/src/views/Campaign/Explore/Panels/Comment/CommentGroup.tsx
- applications/client/src/views/Campaign/Explore/components/BreadcrumbsStyled.tsx
- applications/client/src/views/Campaign/Presentation/Presentation.tsx
- applications/client/src/views/Campaign/Presentation/PresentationItem.tsx
- applications/client/src/views/Campaign/Presentation/PresentationItemHeader.tsx
- applications/client/src/views/Campaign/Presentation/PresentationNavBar.tsx
- applications/client/src/views/Campaign/Presentation/SlideSelector.tsx
- applications/redeye-e2e/src/integration/e2e/blueteam/presentation-mode-navigation.cy.js
- applications/redeye-e2e/src/integration/e2e/redteam/presentation-mode-navigation.cy.js
Added a different to presentation mode to:
- improve information hierarchy 
- give the host name more prominence
- consolidate the navigation elements
- better handle cases where there are multiple hosts or beacons
> Presentation Mode - Layout Updates

- applications/client/src/views/Campaign/Explore/Panels/Command/RawLogsDialog.tsx
> RawLogsDialog - minor style updates
